apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: karavan-operator-role
rules:
  - apiGroups: [ "apps", "extensions" ]
    resources: [ "serviceaccounts", "deployments", "services", "routes", "persistentvolumes", "persistentvolumeclaims"]
    verbs: [ "*" ]
  - apiGroups: [ "tekton.dev" ]
    resources: [ "pipelinetasks", "pipelines" ]
    verbs: [ "*" ]
  - apiGroups: [ "rbac.authorization.k8s.io" ]
    resources: [ "roles", "rolebindings" ]
    verbs: [ "*" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: karavan-operator
  name: karavan-operator
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: karavan-operator-role
subjects:
  - kind: ServiceAccount
    name: karavan-operator