apiVersion: camel.apache.org/v1
kind: Karavan
metadata:
  name: karavan
  namespace: karavan
spec:
  instances: 1
  auth: public
  nodePort: 30668
  environment: demo
  runtimes: quarkus,spring-boot
  gitPullInterval: 10s
